# Turret spec reference

# distro is the Linux-based distro in the base image;
# one of "alpine", "arch", "chimera", "debian", "fedora", "opensuse" and "void";
# required;
# case-insensitive
#
#distro = ""

# Name for the image that we'll be committing;
# required;
# will be resolved with respect to `localhost`
#
#repository = ""

# Tag for the image that we'll be committing;
# if blank, only `latest` will be created
#
#tag = ""

# Environment variables to set before committing the image
#
#env = {}

# Annotations to set before committing the image
#
#annotations = {}

# Whether to preserve the image history and file timestamps
#
#keep-history = false

[from]

# Name of the base image; must contain the fully qualified registry, e.g.,
# registry.fedoraproject.org/fedora;
# required
#
#repository = ""

# Tag of the base image;
# required
#
#tag = ""

[packages]

# Whether to upgrade pre-installed packages
#
#upgrade = false

# List of packages to install
#
#install = []

# Whether to clean package caches after upgrading or installing packages
#
#clean = false

[user]

# User's unique human-readable identifier;
# must contain only digits, letters, hyphens, periods and underscores;
# can't start or end with a special character;
# can't consist entirely of numbers;
# can't be equal to "." or ".."
#
#name = "user"

# User's unique numeric identifier;
# either 0 or an integer from 1000 to 60000, inclusive;
# the default value of 0 tells the program to determine the UID automatically
#
#id = 0

# Whether to create a user group that has the same name as the user and whose
# GID is equal to the user's UID
#
#user-group = false

# List of additional groups of which the user should be a member
#
#groups = []

# GECOS field text (usually a generic descriptor or full name)
#
#comment = ""

# Create a home directory for the user in /home
#
#create-home = false

# User's interactive shell;
# can be an absolute path or a PATH-resolvable command;
# useful in development containers
#
#shell = ""

[[copy]]

# Context directory for the files to copy over to the working container;
# if a relative path, then it must be local to the containing directory;
# if omitted, then the base is the containing directory
#
#base = ""

# Absolute path to the destination on the working container's file system;
# required
#
#dest = ""

# Absolute or relative paths to source files on the host's file system;
# required;
# may contain gitignore-style glob patterns
#
#srcs = []

# Source files in the base directory to exclude from the copy operation;
# may contain gitignore-style glob patterns
#
#excludes = []

# Set the mode of the copied files to this integer, e.g., 0o600
#
#mode = 0o0

# Transfer ownership of the copied files to this user
#
#owner = ""

# Remove all SUID and SGID bits from the files copied to the working container
#
#remove-s = false

[security.special-files]

# Whether to unset the SUID and SGID bits on all files in the working container
# that have one, searching only real (non-device) file systems
#
#remove-s = false

# List of absolute paths to files whose SUID/SGID bit should be preserved (a
# file need not possess a special bit to be listed)
#
#excludes = []

[backends]

# The package manager in the base image;
# one of "apk", "apt", "dnf", "pacman", "xbps" and "zypper";
# case-insensitive
#
#package = ""

# The user and group management utility in the base image;
# one of "busybox" and "shadow";
# case-insensitive
#
#user = ""

# The implementation of the find utility in the base image;
# one of "bsd", "busybox" and "gnu";
# case-insensitive
#
#finder = ""
