# Turret spec reference

[this]

# Linux-based distro in the base image;
# one of "alpine", "arch", "chimera", "debian", "fedora", "opensuse" and "void";
# required;
# case-insensitive
#
#distro = ""

# Name for the image we'll be committing;
# comprises a fully qualified domain and path;
# required;
#
#repository = ""

# Human-readable identifier for the image we'll be committing;
# when blank, only the `latest` tag will be created
#
#tag = ""

# Preserve the image history and file timestamps
#
#keep-history = false

[from]

# Name of the base image;
# comprises a fully qualified domain and path;
# e.g., registry.fedoraproject.org/fedora;
# required
#
#repository = ""

# Human-readable identifier for a manifest in the repository;
# required
#
#tag = ""

# Unique content identifier;
# e.g., sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
#
#digest = ""

[packages]

# Upgrade pre-installed packages
#
#upgrade = false

# Install one or more packages
#
#install = []

# Clean package caches after upgrading or installing packages
#
#clean = false

[user]

# User's unique human-readable identifier;
# must contain only digits, letters, hyphens, periods and underscores;
# can't start or end with a special character;
# can't consist entirely of digits;
# must not be longer than 32 characters;
# required when the user table is present in the spec
#
#name = ""

# User's unique numeric identifier;
# either 0 or an integer from 1000 to 60000, inclusive;
# the default value of 0 tells the program to determine the UID automatically
#
#id = 0

# Create a user group that has the same name as the user and whose GID is equal
# to the user's UID
#
#user-group = false

# Groups to which to add the user
#
#groups = []

# GECOS field text;
# must be no longer than 255 characters
#
#comment = ""

# Create a home directory for the user in /home
#
#create-home = false

[[copy]]

# Context directory for the files to copy over to the working container;
# if a relative path, then it must be local to the containing directory;
# if equal to "~" or starts with "~/", then the tilde is expanded to the home
# directory of the user invoking the program;
# when blank, the base is the containing directory
#
#base = ""

# Absolute path to the destination on the working container's file system;
# required
#
#dest = ""

# Paths to source files on the host's file system;
# required (must contain one or more nonempty sources);
# may contain gitignore-style glob patterns
#
#srcs = []

# Source files in the base directory to exclude from the copy operation;
# may contain gitignore-style glob patterns
#
#excludes = []

# Set the mode of the copied files to this integer, e.g., 0o600
#
#mode = 0o0

# Transfer ownership of the copied files to this user
#
#owner = ""

# Remove all SUID and SGID bits from the files copied to the working container
#
#remove-s = false

[security.special-files]

# Unset the SUID and SGID bits on all files in the working container that have
# one, searching only real (non-device) file systems
#
#remove-s = false

# Absolute paths to files in the working container whose SUID and SGID bits
# should be preserved;
# a file need not possess a special bit to be listed
#
#excludes = []

[config]

# Set or update one or more annotations;
# each annotation key must use reverse domain notation
#
#annotations = {}

# Provide contact information for the image maintainer
#
#author = ""

# Set the default command (or the parameters, if an entrypoint is set)
#
#cmd = []

# Describe how the image was built
#
#created-by = ""

# Set the entrypoint
#
#ep = []

# Set or update one or more environment variables
#
#env = {}

# Set or update one or more labels;
# each label key must use reverse domain notation
#
#labels = {}

# Set the default directory in which the entrypoint or command should run;
# must be an absolute path
#
#work-dir = ""

[[config.ports]]

# Expose the port with this number;
# required
#
#number = 0

# Use this transport-layer protocol;
# one of "tcp" and "udp";
# case-insensitive;
# when blank, defaults to "tcp"
#
#protocol = ""

[config.clear]

# Clear all annotations
#
#annotations = false

# Clear the author
#
#author = false

# Clear the command;
# useful when the base image has a command but you want to set a custom
# entrypoint instead
#
#cmd = false

# Unset all environment variables;
# use with caution: many base images use this mechanism to set `PATH`
#
#env = false

# Clear the entrypoint;
# useful when the base image has an entrypoint but you would rather set a
# custom command instead
#
#ep = false

# Clear all labels
#
#labels = false

# Close all exposed ports
#
#ports = false

[backends]

# The package manager in the base image;
# one of "apk", "apt", "dnf", "pacman", "xbps" and "zypper";
# case-insensitive
#
#package = ""

# The user and group management utility in the base image;
# one of "busybox" and "shadow";
# case-insensitive
#
#user = ""

# The implementation of the find utility in the base image;
# one of "bsd", "busybox" and "gnu";
# case-insensitive
#
#finder = ""
