distro = "arch"
repository = "turret/arch-base"
tag = "0.1.0"

[from]
repository = "docker.io/library/archlinux"
tag = "base-20230514.0.150299"

[user]
create = true

[security.special-files]
remove-s = true
