[this]
distro = "arch"
repository = "localhost/hello-arch"
tag = "0.1.0"

[from]
repository = "docker.io/library/archlinux"
tag = "base-20230514.0.150299"

[user]
name = "user"

[security.special-files]
remove-s = true
