[from]
repository = "docker.io/library/debian"
tag = "11.7-slim"
distro = "debian"

[this]
repository = "localhost/hello-debian"
tag = "0.1.0"

[user]
name = "user"

[security.special-files]
remove-s = true
