[from]
repository = "registry.fedoraproject.org/fedora"
tag = "38-x86_64"
distro = "fedora"

[this]
repository = "localhost/hello-fedora"
tag = "0.1.0"

[user]
name = "user"

[security.special-files]
remove-s = true
