[this]
distro = "openSUSE"
repository = "localhost/hello-opensuse"
tag = "0.1.0"

[from]
repository = "registry.opensuse.org/opensuse/leap"
tag = "15.5"

[user]
name = "user"

[security.special-files]
remove-s = true
