distro = "openSUSE"
repository = "opensuse-base"
tag = "0.1.0"

[from]
repository = "registry.opensuse.org/opensuse/leap"
tag = "15.5"

[user]
create = true

[security]
special-files = [
  "/sbin/unix2_chkpwd",
  "/sbin/unix_chkpwd",
  "/usr/bin/chage",
  "/usr/bin/chfn",
  "/usr/bin/chsh",
  "/usr/bin/expiry",
  "/usr/bin/gpasswd",
  "/usr/bin/mount",
  "/usr/bin/newgidmap",
  "/usr/bin/newgrp",
  "/usr/bin/newuidmap",
  "/usr/bin/passwd",
  "/usr/bin/su",
  "/usr/bin/umount",
  "/usr/bin/wall",
  "/usr/bin/write",
  "/usr/lib/utempter/utempter",
]
