[this]
distro = "void"
repository = "void-base"
tag = "0.1.0"

[from]
repository = "ghcr.io/void-linux/void-linux"
tag = "20230204RC01-full-x86_64"

[user]
name = "user"

[security.special-files]
remove-s = true
