name: ci-go
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/go-ci.yml'
      - '.golangci.yml'
      - 'go.mod'
      - 'cmd/**.go'
      - 'pkg/**.go'

  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/go-ci.yml'
      - '.golangci.yml'
      - 'go.mod'
      - 'cmd/**.go'
      - 'pkg/**.go'

permissions:
  contents: read

jobs:
  debug:
    runs-on:
      - ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20.2'

      - name: Print Go environment
        run: go env

      - name: Setup linters
        run: make setup

      - name: Check Go code
        run: make check
