name: ci-go
on:
  push:
    branches:
      - main
    paths:
      - '.golangci.yml'
      - 'Makefile'
      - 'cmd/**.go'
      - 'go.mod'
      - 'go.sum'
      - 'internal/**.go'
      - 'pkg/**.go'

  pull_request:
    branches:
      - main
    paths:
      - '.golangci.yml'
      - 'Makefile'
      - 'cmd/**.go'
      - 'go.mod'
      - 'go.sum'
      - 'internal/**.go'
      - 'pkg/**.go'

  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    runs-on:
      - ubuntu-22.04

    steps:
      - name: Update APT index
        run: sudo apt update

      - name: Install compile-time dependencies of Buildah
        run: sudo apt install --quiet --yes libbtrfs-dev libdevmapper-dev libgpgme11-dev

      - name: Checkout last commit on branch main
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20.2'

      - name: Prepare development environment
        run: make setup.linters

      - name: Assert all Go code satisfies quality standards
        run: make check
