name: ci-go
on:
  push:
    branches:
      - main
    paths:
      - '.golangci.yml'
      - 'go.mod'
      - 'cmd/**.go'
      - 'pkg/**.go'

  pull_request:
    branches:
      - main
    paths:
      - '.golangci.yml'
      - 'go.mod'
      - 'cmd/**.go'
      - 'pkg/**.go'

  workflow_dispatch:

permissions:
  contents: read

jobs:
  debug:
    runs-on:
      - ubuntu-22.04

    steps:
      - name: Update apt package index
        run: sudo apt update

      - name: Install Buildah dependencies
        run: sudo apt install -qy libbtrfs-dev libdevmapper-dev libgpgme11-dev

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20.2'

      - name: Setup linters
        run: make setup

      - name: Check Go code
        run: make check
